# Generated by Django 3.0.8 on 2020-08-13 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Touroperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_contact_person', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=30)),
                ('touroperator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('repeat_email', models.EmailField(max_length=99)),
                ('age', models.IntegerField()),
                ('number_of_persons', models.IntegerField(null=True)),
                ('destinations', models.CharField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Puno', 'Puno'), ('Cusco', 'Cusco')], max_length=100, null=True)),
                ('touroperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Touroperator')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
