# Generated by Django 3.0.8 on 2020-08-13 09:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='destinations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Puno', 'Puno'), ('Cusco', 'Cusco')], max_length=24, null=True),
        ),
    ]
