# Generated by Django 3.0.8 on 2020-08-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200814_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touroperator',
            old_name='test',
            new_name='touroperator_test',
        ),
    ]
