# Generated by Django 3.0.8 on 2020-08-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_auto_20200814_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroperator',
            name='touroperator_test',
        ),
        migrations.AlterField(
            model_name='touroperator',
            name='touroperator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
