# Generated by Django 3.0.8 on 2020-08-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20200814_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='touroperator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Touroperator'),
        ),
    ]
